#!/bin/bash


arp_db="/var/log/arp_db.log"
recipient=""
sender=""
smtp_server=""
smtp_user=""
smtp_pass=""
alert_msg_file="/tmp/alert.txt"


_DEBUG="on"
function DEBUG()
{
 [ "$_DEBUG" == "on" ] &&  $@
}

DEBUG echo '[DEBUG] started support-script'

#clean arp database
[ -f $arp_db ] && rm -f $arp_db; touch $arp_db
while read line
do
	ip=""
	mac=""
	type=""
	timestamp=$(echo $line| cut -d " " -f1)
	protocol=$(echo $line| cut -d " " -f2| sed -e 's/,$//g')

	if [ "$protocol" = "ARP" ] 
		then
#		DEBUG set -x
		type=$(echo $line| cut -d " " -f3)
#		DEBUG set +x


		if [ "$type" = "Reply" ]
		then
			ip=$(echo $line| cut -d " " -f4)
			mac=$(echo $line| cut -d " " -f6| sed -e 's/,$//g')
			found=$(grep -q $ip $arp_db ; echo $?)
			if [ "$found" = "1" ] #IP NOT in the DB
				then
				echo -e "$mac $ip" >> $arp_db
				DEBUG echo "[DEBUG] New entry in ARP database for MAC $mac attached to IP $ip"
			else # IP in the DB
				mac_orig=$(egrep "$ip\$" $arp_db | cut -d " " -f1)
				if [ "$mac_orig" = "$mac" ]
					then
					DEBUG echo "MAC $mac attached to IP $ip already in the DB; skipping"
				else
					echo "!!!ATTACK DETECTED!!! The host with MAC: $mac is using the IP $ip that belongs to MAC: $mac_orig"
					#notificare e-mail
					if [ "$recipient" != "" ]
						then
						echo "!!!ATTACK DETECTED!!! The host with MAC: $mac is using the IP $ip that belongs to MAC: $mac_orig" > $alert_msg_file
						sendmail $recipient -f $sender -S $smtp_server -au $smtp_user -ap $smtp_pass < $alert_msg_file
					fi
				fi
			fi
		fi
	fi
	echo "$timestamp $protocol $type $ip $mac"
#echo $line
done
